import Egyptian from './Egyptian';
import CityName from '@civ-clone/core-civilization/CityName';
import { instance as cityNameRegistryInstance } from '@civ-clone/core-civilization/CityNameRegistry';

([
  'Cairo',
  'Alexandria',
  'Gizeh',
  'Shubra El-Kheima',
  'Port Said',
  'Suez',
  'Luxor',
  'al-Mansura',
  'El-Mahalla El-Kubra',
  'Tanta',
  'Asyut',
  'Ismailia',
  'Fayyum',
  'Zagazig',
  'Aswan',
  'Damietta',
  'Damanhur',
  'al-Minya',
  'Beni Suef',
  'Qena',
  'Sohag',
  'Hurghada',
  '6th of October City',
  'Shibin El Kom',
  'Banha',
  'Kafr el-Sheikh',
  'Arish',
  'Mallawi',
  '10th of Ramadan City',
  'Bilbais',
  'Marsa Matruh',
  'Idfu',
  'Mit Ghamr',
  'Al-Hamidiyya',
  'Desouk',
  'Qalyub',
  'Abu Kabir',
  'Kafr el-Dawwar',
  'Girga',
  'Akhmim',
  'Matarey',
] as string[]).forEach((name, i): void =>
  cityNameRegistryInstance.register(new CityName(name, Egyptian, i === 0))
);
