"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Egyptian_1 = require("./Egyptian");
const CityName_1 = require("@civ-clone/core-civilization/CityName");
const CityNameRegistry_1 = require("@civ-clone/core-civilization/CityNameRegistry");
[
    'Cairo',
    'Alexandria',
    'Gizeh',
    'Shubra El-Kheima',
    'Port Said',
    'Suez',
    'Luxor',
    'al-Mansura',
    'El-Mahalla El-Kubra',
    'Tanta',
    'Asyut',
    'Ismailia',
    'Fayyum',
    'Zagazig',
    'Aswan',
    'Damietta',
    'Damanhur',
    'al-Minya',
    'Beni Suef',
    'Qena',
    'Sohag',
    'Hurghada',
    '6th of October City',
    'Shibin El Kom',
    'Banha',
    'Kafr el-Sheikh',
    'Arish',
    'Mallawi',
    '10th of Ramadan City',
    'Bilbais',
    'Marsa Matruh',
    'Idfu',
    'Mit Ghamr',
    'Al-Hamidiyya',
    'Desouk',
    'Qalyub',
    'Abu Kabir',
    'Kafr el-Dawwar',
    'Girga',
    'Akhmim',
    'Matarey',
].forEach((name, i) => CityNameRegistry_1.instance.register(new CityName_1.default(name, Egyptian_1.default, i === 0)));
//# sourceMappingURL=registerCityNames.js.map